import React from "react";

const ChatMessage = ({ content, from, imageUrl }) => {
  return (
    <div className={`chat-message from-${from}`}>
      <div className="message-content">
        {/* If the message is from the assistant */}
        {from === "chatgpt" ? (
          <>
            {/* If the message is an image message */}
            {imageUrl ? (
              <div className="image-message">
                <img
                  src={imageUrl}
                  alt="Generated by DALLE API"
                  style={{ width: "100%", height: "auto" }}
                />
                <p>{content}</p>
              </div>
            ) : (
              // Otherwise, display the text
              <p>{content}</p>
            )}
          </>
        ) : (
          // If the message is from the user, display the text
          <p>{content}</p>
        )}
      </div>
    </div>
  );
};

export default ChatMessage;
